---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rsyslog-client-config
data:
  90-k8s-client.conf.template: |
    global(
        maxMessageSize="64k"
    )

    module(load="imfile"
        mode="polling"
        pollinginterval="3"
    )
    module(load="mmjsonparse")
    module(load="mmkubernetes"
        tls.cacert="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        tokenfile="/var/run/secrets/kubernetes.io/serviceaccount/token"
    )

    template(name="all-json-template" type="string"
        string="%$!all-json:json%\n"
    )

    ruleset(name="k8s-client") {
        action(type="mmjsonparse" cookie="")

        action(type="mmkubernetes")

        set $!cluster_name = "${CLUSTER_NAME}";
        # set $!kube!namespace_name = $!kubernetes!namespace_name;
        # set $!kube!pod_name = $!kubernetes!pod_name;

        # unset $!kubernetes;
        # set $!kubernetes = $!kube;
        # unset $!kube;

        unset $!stream;
        unset $!time;
        unset $!metadata;
        unset $!docker;

        action(
            type="omfwd"
            template="all-json-template"
            target="${RSYSLOG_TARGET}"
            port="${RSYSLOG_PORT}"
            protocol="${RSYSLOG_PROTOCOL}"
        )
    }

    input(type="imfile"
        file="/var/log/containers/*.log"
        ruleset="k8s-client"
        tag="k8s:"
        reopenontruncate="on"
    )

  90-inotify.conf: |
    fs.inotify.max_user_watches = 131072

  docker-entrypoint.sh: |
    #!/bin/bash

    apt update
    dpkg -l gettext-base >& /dev/null || apt -y install gettext-base
    dpkg -l rsyslog-kubernetes >& /dev/null || apt -y install rsyslog-kubernetes

    envsubst < /etc/rsyslog.d/90-k8s-client.conf.template > /etc/rsyslog.d/90-k8s-client.conf

    sysctl -p /etc/sysctl.d/90-inotify.conf
    # echo '131072' > /proc/sys/fs/inotify/max_user_watches
    ### (while true; do sleep $[6*60*60]; kill -HUP 1; done) &> /dev/null &

    exec "$@"
---
