---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rsyslog-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rsyslog-agent
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rsyslog-agent-binding
roleRef:
  kind: ClusterRole
  name: rsyslog-agent
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: rsyslog-agent
  namespace: kube-system
---
